databases:
  - name: bibliopola
    databaseName: bibliopola
    user: admin
    region: singapore

services:
  - type: web
    name: bibliopola
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bibliopola
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
